### ISSUE TITLE
สร้าง NuGet package ชื่อ BCircle.CentralLogProvider

### ISSUE THREAD

**Issue by wk-j** [bcircle-intern/central-logger#10]
นำ dll ในโปรเจค CentralLogProvider ขึ้น nuget.org โดยใช้ชื่อว่า BCircle.ControlLogProvider

**Comment by nattapatee** [comment]
https://www.nuget.org/packages/CentralLogProvider/

**Comment by wk-j** [comment]
ชื่อ `BCircle.CentralLogProvider`

**Comment by nattapatee** [comment]
https://www.nuget.org/packages/BCircle.CentralLogProvider/0.1.0
